application: bierhier-1
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.(html|css|gif|png|jpg|svg|JPG))$
  static_files: \1
  upload: .+\.(html|css|gif|png|jpg|svg|JPG)$
  application_readable: true

- url: /.*
  static_files: index.html
  upload: index.html
  application_readable: true